## If we remove the needs from the second job, will it start immediately or run in parallel
## updated github action .github/workflows
name: day-2
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the new code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

  deploy:
    needs: [test]  # Remove this line if you want it to run in parallel
    runs-on: ubuntu-latest
    steps:
      - name: Deploy application
        run: npm start
