name: Print GitHub Context on Issue Events test

on: workflow_dispatch
#  issues:
#    types: [opened, edited, closed]
  

jobs:
  show-context:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub context
        run: echo '${{ toJson(github) }}'
